
env:
  global:
    - CONAN_USERNAME: "conan"
    - CONAN_CHANNEL: "testing"
    - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63

      - <<: *osx
        osx_image: xcode8.3

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
