
env:
  global:
    - CONAN_USERNAME: "conan"
    - CONAN_CHANNEL: "testing"
    - CONAN_STABLE_BRANCH_PATTERN: "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc73

      - <<: *osx

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
