
env:
  global:
    - CONAN_USERNAME: "conan"
    - CONAN_CHANNEL: "testing"
    - CONAN_STABLE_BRANCH_PATTERN: "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
windows: &windows
   os: windows
   language: shell
matrix:
   include:
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc54

      - <<: *osx
        osx_image: xcode8.3

      - <<: *windows
        env: CONAN_VISUAL_VERSIONS: 15

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
