name: CI

on:
  push:
    branches:
      - master
      - testing/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-18.04]
    env:
        CONAN_USERNAME: "conan"
        CONAN_CHANNEL: "testing"
        CONAN_REMOTES: https://api.bintray.com/conan/anton-matosov/general
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        CONAN_STABLE_BRANCH_PATTERN: "v\\d+\\.\\d+\\.\\d+"
        CONAN_USER_HOME: "~/.conan"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Get pip cache
        id: pip-cache
        run: |
          python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v1
        with:
          path: ${{ env.CONAN_USER_HOME }}
          key: ${{ runner.os }}-conan-${{ hashFiles('**/build.py') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install CPT
        run: |
          pip install -r requirements.txt --upgrade

      - name: Build only
        if: github.event_name == 'pull_request'
        run: python build.py

      - name: Build and publish
        if: github.event_name == 'push'
        env:
          CONAN_UPLOAD: https://api.bintray.com/conan/anton-matosov/general
        run: python build.py

      - name: Build and publish stable
        if: github.event_name == 'release'
        env:
          CONAN_CHANNEL: "stable"
          CONAN_UPLOAD: https://api.bintray.com/conan/anton-matosov/general
        run: python build.py
